### PR TITLE
Password reset form updated

### PR DESCRIPTION
**Pull request by jab098**

### CODE REVIEW

**Comment by Mattie2** [comment]
you need to make the form actually part of the page. Currently the form is overlayed above the header which isn't correct
image

**Comment by Mattie2** [comment]
you have broken the reset password form
image
please can you test before creating a merge request

**Comment by jab098** [comment]
> you have broken the reset password form image please can you test before creating a merge request

I tested before sending a request and now tested after, i cannot seem to replicate your issue. It has been working just fine for me and redirecting to the reset complete page.

**Comment by Mattie2** [comment]
> you need to make the form actually part of the page. Currently the form is overlayed above the header which isn't correct image

actually, just remove the base.html file as we don't need the header on this page

**Comment by Mattie2** [comment]
please remove base.html from all 4 password reset pages

**Comment by Mattie2** [comment]
please update password_reset_complete.html (you need to enter a valid email to reach this page) you can see the valid emails in the admin view, and a link will show in the terminal
image
image

**Comment by Mattie2** [comment]
please update password_reset_complete.html - must actually reset the password to reach there

**Comment by jab098** [comment]
> please update password_reset_complete.html (you need to enter a valid email to reach this page) you can see the valid emails in the admin view, and a link will show in the terminal image image

This page and its function isn't part of this pull request, only updating the UI for reset form, complete and logged out pages.
I have removed the base.html as requested and all should be good now

**Pull request merged**
